apiVersion: v1
kind: ConfigMap
metadata:
  name: training-config
  namespace: ml-training
data:
  training_config.yaml: |
    batch_size: 512
    epochs: 4
    patience: 2

    # AdamW optimizer params
    lr: 0.001
    weight_decay: 0.01